<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Suite_ChangePassword</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>32c89ec5-8675-4915-abe9-54c015c71a63</testSuiteGuid>
   <testCaseLink>
      <guid>a771e6c4-d82a-4e8f-a40c-6f4618c15842</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_ChangePassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6d021ca6-dac3-4601-a906-8894bdfa8a00</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_UpdateProfile</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6d021ca6-dac3-4601-a906-8894bdfa8a00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mat_Khau_Hien_Tai</value>
         <variableId>2c6af46b-8a68-444e-baba-5fdb71ddb295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6d021ca6-dac3-4601-a906-8894bdfa8a00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mat_Khau_Moi</value>
         <variableId>e195b344-ceca-4508-81c5-6e0e08ef382a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6d021ca6-dac3-4601-a906-8894bdfa8a00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ket_qua_mong_doi</value>
         <variableId>141e448d-7f92-465e-8b13-3d8b9c6f15b9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
