<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ngh di_longBreakDuration</name>
   <tag></tag>
   <elementGuidId>d3bb9f06-3725-47d1-ab5f-023b03491c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;longBreakDuration&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='longBreakDuration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1581a271-901c-40a4-ada9-30f4a9ccaf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>49544902-a380-40ab-a36d-d85e8bd6bf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>366571c0-6237-4ee6-b1ca-19486e6ac500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a18d40c9-c8b0-4875-9122-afe1cb58c9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jHiZoE kVASma</value>
      <webElementGuid>a891c978-0d3a-4d8d-83c8-2d321a690f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a0e30c2c-c499-4150-a66b-7a2f0e4fb226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>88afe126-eae9-4cd7-9f3d-3dc2d41062f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>longBreakDuration</value>
      <webElementGuid>2fe7f382-9d8b-43dc-9a7e-c87889f43f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gVrasc btEuEu&quot;]/div[@class=&quot;sc-nVSyK hTjewX&quot;]/div[@class=&quot;sc-gxDBpp klruer&quot;]/form[1]/div[6]/div[1]/div[@class=&quot;sc-gZtkdK kAjTll&quot;]/input[@class=&quot;sc-jHiZoE kVASma&quot;]</value>
      <webElementGuid>7dec5f17-5c88-4389-9cf3-f6b8f2d1d0aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='longBreakDuration']</value>
      <webElementGuid>965e4298-35f4-40ae-b41d-b1bcafcfbb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/form/div[6]/div/div[4]/input</value>
      <webElementGuid>8f1d04fb-22bc-4051-ad68-9bf5b119c3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>df10b403-cbaf-4f8b-967b-2ab0f8873863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '15' and @type = 'number' and @name = 'longBreakDuration']</value>
      <webElementGuid>6f161512-af92-4cd5-af7f-b156866ad0da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
