<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M t_description</name>
   <tag></tag>
   <elementGuidId>b1ce9f89-e4a2-491b-829c-e0a654c9e62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e055e78c-e422-4a10-a64e-7f80736eedfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>VD: Tập trung học Reading với phương pháp Pomodoro</value>
      <webElementGuid>f3716494-086d-4049-9bc8-c8b4a3b14552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jHiZoE kVASma</value>
      <webElementGuid>31e094d1-d784-4371-8945-d87ac6d78d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c01c795-3844-4ce5-bb65-477309af931f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>3a24b129-487f-4dfe-8930-c80babadff9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gVrasc btEuEu&quot;]/div[@class=&quot;sc-nVSyK hTjewX&quot;]/div[@class=&quot;sc-gxDBpp klruer&quot;]/form[1]/div[@class=&quot;sc-gZtkdK kAjTll&quot;]/input[@class=&quot;sc-jHiZoE kVASma&quot;]</value>
      <webElementGuid>9b705af9-b9f8-425e-a17a-dab840c20a91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='description']</value>
      <webElementGuid>173c9a46-52bd-4717-87e7-c1d7bfe295df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/form/div[2]/input</value>
      <webElementGuid>9f689aba-f485-4eab-b129-ea1cdc2636e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bf4df543-356a-4d9d-913f-8a6609325e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'VD: Tập trung học Reading với phương pháp Pomodoro' and @type = 'text' and @name = 'description']</value>
      <webElementGuid>a4436645-9a56-4fce-ac99-f81172b5bc03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
