<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_EnglishMasterTI  C TI KHONBT U</name>
   <tag></tag>
   <elementGuidId>62f9cfd3-df08-4617-bb6e-f1a0a73ca40d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.sc-blIAwI.gEhnFo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>32b1b9b8-3a16-410d-a626-0a07ba8d941c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-blIAwI gEhnFo</value>
      <webElementGuid>d3841b1e-6203-4049-a836-905fac3909b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EnglishMasterTÔI ĐÃ CÓ TÀI KHOẢNBẮT ĐẦU</value>
      <webElementGuid>c266a080-95b0-4a1e-ba2c-c785a1336079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gsJsQu xOwem&quot;]/nav[@class=&quot;sc-blIAwI gEhnFo&quot;]</value>
      <webElementGuid>307eefe6-49f0-4a53-a41e-dcc416392f9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav</value>
      <webElementGuid>4908d3b5-3ca9-4101-b758-00387d52287f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>f378f6c1-1a47-4604-86c2-e3b74461636d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'EnglishMasterTÔI ĐÃ CÓ TÀI KHOẢNBẮT ĐẦU' or . = 'EnglishMasterTÔI ĐÃ CÓ TÀI KHOẢNBẮT ĐẦU')]</value>
      <webElementGuid>e922739f-07a7-4f99-9b77-6c7e82883173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
