<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ReadingListeningWritingSpeakingVocab_b1fef0</name>
   <tag></tag>
   <elementGuidId>86c95e33-8f25-4591-aab0-6121369a7a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;skill&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='skill']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87a9da08-1461-4d1f-9c81-d169ddb0b339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skill</value>
      <webElementGuid>77c0cb44-64d5-479c-9b20-bd2b9a9a70fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cNFoqh bVyUIo</value>
      <webElementGuid>4bdd4e30-4f96-410c-9881-5ffb74745680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ReadingListeningWritingSpeakingVocabularyGrammarMixed</value>
      <webElementGuid>83792f7f-75df-4bd6-a6df-e1c0e1700334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gVrasc btEuEu&quot;]/div[@class=&quot;sc-nVSyK hTjewX&quot;]/div[@class=&quot;sc-gxDBpp klruer&quot;]/form[1]/div[@class=&quot;sc-gZtkdK kAjTll&quot;]/select[@class=&quot;sc-cNFoqh bVyUIo&quot;]</value>
      <webElementGuid>d56ab70e-98ea-41d0-a502-00be19c7f203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='skill']</value>
      <webElementGuid>5c1bcb0c-6d09-4233-874b-052a420dd2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/form/div[4]/select</value>
      <webElementGuid>f73d5c4d-3e79-48db-bd1c-7247870cbe6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kỹ năng cần tập trung'])[1]/following::select[1]</value>
      <webElementGuid>e2d2c100-ef96-4a62-a7f2-74aff4b86576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại mục tiêu'])[5]/following::select[2]</value>
      <webElementGuid>9fa97ea0-289a-4d02-9b5a-619453fdaf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>6bce0673-1612-4fe3-8ed0-6cb3ee67a15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'skill' and (text() = 'ReadingListeningWritingSpeakingVocabularyGrammarMixed' or . = 'ReadingListeningWritingSpeakingVocabularyGrammarMixed')]</value>
      <webElementGuid>c2069cc3-3b1c-4627-bc70-a613b0ebb7dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
