<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hn hon thnh_deadline</name>
   <tag></tag>
   <elementGuidId>fce4ea45-e1d0-4083-b092-675e6f4e39b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;deadline&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='deadline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab82b993-877a-4656-b1fd-c94a51ca5a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jHiZoE kVASma</value>
      <webElementGuid>ccb84bbe-ac4f-48c4-9616-02a0bf6f6622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>3e8c2a97-cf66-4a22-98e2-2d3be5a4640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deadline</value>
      <webElementGuid>3169471c-2e7b-46c0-9167-2a7a59f4065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gVrasc btEuEu&quot;]/div[@class=&quot;sc-nVSyK hTjewX&quot;]/div[@class=&quot;sc-gxDBpp klruer&quot;]/form[1]/div[@class=&quot;sc-gZtkdK kAjTll&quot;]/input[@class=&quot;sc-jHiZoE kVASma&quot;]</value>
      <webElementGuid>84c9fa58-8e9f-4a8e-bb39-98eeb618b0d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='deadline']</value>
      <webElementGuid>c25d53eb-3508-472f-9478-a51a082b0194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/form/div[6]/input</value>
      <webElementGuid>9e4ac3a5-29db-4061-b3c0-7b6c5edc5cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>0d4caa26-10bd-44ad-8c47-5b7a2a595fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'deadline']</value>
      <webElementGuid>20ce5ca3-1d4a-4263-9ca3-31563b5c183e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
